"""
This module only defines interfaces. Subclasses should implement all abstract methods.
"""
import torch.nn as nn
import torch
import torch.nn.functional as F
from typing import List, Optional, Sequence, Tuple, Union

class VQVAEBase(nn.Module):
    def __init__(self, vocab_size: int=0, embedding_dim: int=128):
        super().__init__()
        self.vocab_size = vocab_size
        self.embedding_dim = embedding_dim

        self.encoder:nn.Module = None
        self.decoder:nn.Module = None

        self.quantizer: VectorQuantizerBase = None
    def forward(self, p_BJDs: torch.Tensor, hasLoss=True):
        """
        Use encoder, quantizer and decoder to encode, quantize and decode the input features.

        Args:
            p_BJD: Input poses with shape (B, J, D) before encoding
            hasLoss: Whether to return loss
        
        Returns:
            dict: {
                - 'loss': Total loss,
                - 'vq_loss': VQ loss,
                - 'recon_loss': Reconstruction loss,
                - 'alignment_loss': Alignment loss,
                - 'multi_fhats': Reconstructed features,
                - 'multi_phats': Reconstructed poses,
                - 'idx_Bl': Indices for each scale,
                - 'prev_embedding': Embeddings before a transition
                }
        """
        raise NotImplementedError("forward method must be implemented in subclasses")
    
    def idxbl_to_multi_pose(self, idx_bl:list[torch.Tensor])->list[torch.Tensor]:
        """
        Convert multi-scale indices to multi pose.
        
        Args:
            idx_bl: Ground truth multi-scale indices
            
        Returns:
            multi pose
        """
        raise NotImplementedError("idxbl_to_multi_pose method must be implemented in subclasses")
    
    def prev_embedding_to_multi_pose(self, prev_embedding:list[torch.Tensor])->list[torch.Tensor]:
        """
        Convert embeddings before a transition to multi pose.
        
        Args:
            prev_embedding: Embeddings before a transition
            
        Returns:
            multi pose
        """
        raise NotImplementedError("prev_embedding_to_multi_pose method must be implemented in subclasses")
    
    def first_pose_quantize(self, first_pose:torch.Tensor)->dict[str, torch.Tensor]|None:
        """
        Generate the first pose for inference.
        
        Args:
            first_pose: First pose (B, J, F)
            
        Returns:
            quantizer_output
            if return None, the first embedding is generated by the ar.
        """
        
        return None
       
    
    @torch.no_grad()
    def reset_dead_codebook_after_one_epochs(self, p_BJD:list[torch.Tensor])->int:
        return 0
    
    def extra_repr(self):
        return "VQVAE"

class VectorQuantizerBase(nn.Module):
    """
    Abstract base class for vector quantizers.
    Defines the interface that all vector quantizer implementations should follow.
    """
    
    def __init__(self, vocab_size: int, Cvae: int, beta: float, using_znorm:bool):
        """
        Initialize the vector quantizer base.
        
        Args:
            vocab_size: Size of the codebook/ vocabulary
            Cvae: Dimension of the codebook embeddings
            beta: Commitment loss weighting factor
            using_znorm: Whether to use z-normalization. In a word, use cosine distance instead of euclidean distance.
        """
        super().__init__()
        self.vocab_size:int = vocab_size
        self.Cvae:int = Cvae
        self.beta: float = beta
        self.using_znorm:bool = using_znorm

        # Codebook embeddings
        self.embedding = nn.Embedding(self.vocab_size, self.Cvae)
        # Initialize with a standard normal distribution
        self.embedding.weight.data.normal_()
    def forward(self, f_BJD: torch.Tensor, hasLoss=True, gt_idx=-1)->dict[str, torch.Tensor]:
        """
        Quantize the input features.
        
        Args:
            f_BChw: Input features with shape (B, C, H, W)
            hasLoss: Whether to return the loss.
            begin_si: The start index of the v patch scale.
            end_si: The end index of the v patch scale.
        Returns:
            dict {
                - 'loss': VQ loss,
                - 'multi_fhats': Multi-scale reconstructed features,
                - 'idx_Bl': Indices for each scale,
                - 'prev_embedding': Embeddings before a transition}
        """
        raise NotImplementedError("forward method must be implemented in subclasses")
    
    def idxBl_to_prev_embedding(self, idx_Bl: List[torch.Tensor]) -> list[torch.Tensor]:
        """
        Convert multi-scale indices to embeddings before a transition.
        
        Args:
            idx_Bl: Ground truth multi-scale indices
            
        Returns:
            embeddings before a transition tensor
        """
        raise NotImplementedError("idxBl_to_prev_embedding method must be implemented in subclasses")

    def prev_embedding_to_multi_fhat(self, h_BJD:list[torch.Tensor], gt_idx=-1) -> list[torch.Tensor]:
        """
        Convert embeddings to multi-scale feature representation.
        
        Args:
            h_BJD: Multi-scale embeddings
            gt_idx: gt patch index
        Returns:
            multi-scale feature representation
        """
        raise NotImplementedError("prev_embedding_to_multi_fhat method must be implemented in subclasses")
    
    def prev_embedding_to_any_fhat(self, h_BJD:list[torch.Tensor], scale:int) -> torch.Tensor:
        """
        Convert embeddings to any-sclae feature representation.
        
        Args:
            h_BJD: Multi-scale embeddings
        Returns:
            any scale feature representation
        """
        raise NotImplementedError("prev_embedding_to_any_fhat method must be implemented in subclasses")
    
    def idxBl_to_multi_fhat(self, idx_Bl: List[torch.Tensor], gt_idx=-1) -> list[torch.Tensor]:
        """
        Convert multi-scale indices to multi-scale reconstructed features.
        
        Args:
            idx_Bl: Ground truth multi-scale indices
            gt_idx: gt patch index
        Returns:
            multi-scale feature representation
        """
        raise NotImplementedError("idxBl_to_multi_fhat method must be implemented in subclasses")

    def idxBl_to_any_fhat(self, idx_Bl: List[torch.Tensor], scale:int) -> torch.Tensor:
        """
        Convert multi-scale indices to multi-scale reconstructed features.
        
        Args:
            idx_Bl: Ground truth multi-scale indices
        Returns:
            any scale feature representation
        """
        raise NotImplementedError("idxBl_to_any_fhat method must be implemented in subclasses")
    
    @torch.no_grad()
    def get_next_autoregressive_input(self, si: int, multi_fhats: list[torch.Tensor], h_BJD: torch.Tensor, gt_idx=-1)-> tuple[torch.Tensor, torch.Tensor]:
        """
        Get the next autoregressive input for inference.
        
        Args:
            si: Current scale index
            multi_fhats: multi reconstructed features
            h_BJD: Current previous embeddings
            gt_idx: gt patch index
            
        Returns:
            Tuple of (updated features, next scale features)
        """
        raise NotImplementedError("get_next_autoregressive_input method must be implemented in subclasses")
    
    @torch.no_grad()
    def training_cache_reset(self):
        """
        Reset the training cache preparing for one training process.
        """
        raise NotImplementedError("training_cache_reset method must be implemented in subclasses")

    def extra_repr(self):
        return "VectorQuantizer"

class VARBase(nn.Module):
    """
    Base class for VAR models, defining a unified interface.
    Subclasses should implement the core training and inference interfaces.
    """
    
    def __init__(self):
        """
        Initialize the VAR model.
        
        Args:
            vae_local: VQVAE model instance
            **kwargs: Other initialization parameters
        """
        super().__init__()
        self.vae_proxy:tuple[VQVAEBase] = None  # VQVAE proxy
        self.vae_quant_proxy:tuple[VectorQuantizerBase] = None  # Quantizer proxy
        
    def forward(self, x_BLC: torch.Tensor, lr_inp:torch.Tensor, idx_Bl_gt:list[torch.Tensor]) -> dict[str, torch.Tensor]:
        """
        Forward pass during training.
        
        Args:
            x_BLC: Input tokens with shape [B, L, C]
            lr_inp: Input data with shape [B, Js, F], e.g. [B, 17, 2]
            idx_Bl_gt: Input token indices with shape [B, L]
        Returns:
            dict: {
                "loss": Total loss,
                "cross_entropy_loss": Cross-entropy loss,
                "idx_Bl_hat": Predicted indices
            }
        """
        raise NotImplementedError("Subclasses must implement the forward method")
    
    # @torch.no_grad()
    def inference(self, lr_inp, top_k=1, top_p=0.96
    ) -> dict[str, list[torch.Tensor]]:
        """
        Inference interface for model inference.
        
        Args:
            lr_inp: Input data with shape [B, L, C]
            top_k: top_k parameter
            top_p: top_p parameter
        Returns:
            dict: {
                "multi_fhats": multi-sclae feature representation,
                "idx_Bl": multi-sclae indices,
                "prev_embedding": embeddings before a transition tensor,
            }
        """
        raise NotImplementedError("Subclasses must implement the inference method")
    
    
    def extra_repr(self) -> str:
        """
        Model string representation, used for printing model information.
        
        Returns:
            String representation of the model
        """
        return "VAR"  # Subclasses may override this method to provide more details
